export const initialReportsData = [
  { 
    id: 'RIETI-ATZ-001', 
    date: '2026-09-10', 
    municipality: 'ATIZAPÁN DE ZARAGOZA', 
    activity: 'Venta en semáforo', 
    risk: 'Alto', 
    riskClass: 'risk-high', 
    status: 'Registrado', 
    statusClass: 'status-citizen', 
    lat: 19.55, lng: -99.25, 
    notasPrivadas: [], 
    notasPublicas: [], 
    isClosed: false, 
    bitacora: [], 
    peligroInmediato: true, 
    posibleDuplicado: false 
  },
  { 
    id: 'RIETI-NAU-002', 
    date: '2026-09-09', 
    municipality: 'NAUCALPAN DE JUÁREZ', 
    activity: 'Limpiaparabrisas', 
    risk: 'Medio', 
    riskClass: 'risk-medium', 
    status: 'En revisión', 
    statusClass: 'status-valid', 
    lat: 19.47, lng: -99.23, 
    notasPrivadas: ['Investigación iniciada por el equipo de campo.'], 
    notasPublicas: ['El caso está siendo revisado por nuestro equipo.'], 
    isClosed: false, 
    bitacora: [{campo: 'Estatus', anterior: 'Registrado', nuevo: 'En revisión', fecha: '11/09/2026 10:30', user: 'Procurador NAU'}], 
    peligroInmediato: false, 
    posibleDuplicado: false 
  },
  { 
    id: 'RIETI-TLA-003', 
    date: '2026-09-08', 
    municipality: 'TLALNEPANTLA DE BAZ', 
    activity: 'Carga y descarga', 
    risk: 'Alto', 
    riskClass: 'risk-high', 
    status: 'Canalizado', 
    statusClass: 'status-canalized', 
    lat: 19.53, lng: -99.19, 
    notasPrivadas: [], 
    notasPublicas: [], 
    isClosed: false, 
    bitacora: [], 
    peligroInmediato: false, 
    posibleDuplicado: true 
  },
  { 
    id: 'RIETI-ATZ-004', 
    date: '2026-09-05', 
    municipality: 'ATIZAPÁN DE ZARAGOZA', 
    activity: 'Mendicidad', 
    risk: 'Alto', 
    riskClass: 'risk-high', 
    status: 'Registrado', 
    statusClass: 'status-citizen', 
    lat: 19.56, lng: -99.24, 
    notasPrivadas: [], 
    notasPublicas: [], 
    isClosed: false, 
    bitacora: [], 
    peligroInmediato: false, 
    posibleDuplicado: false 
  },
];
